# study
study Angular2 and NodeJS



2022-07-13 02:36:15.382546: I tao_bridge/kernels/tao_compilation_cache.cc:359] TaoCompilationCache initiate:
2022-07-13 02:36:15.382585: I tao_bridge/kernels/tao_compilation_cache.cc:360]     tao compiler path: /root/anaconda3/envs/disc-gpu/lib/python3.7/site-packages/blade_disc_tf/tao_compiler_main
2022-07-13 02:36:15.382594: I tao_bridge/kernels/tao_compilation_cache.cc:361]       cache dump path:
2022-07-13 02:36:15.382602: I tao_bridge/kernels/tao_compilation_cache.cc:362]      remove tmp files: 1
2022-07-13 02:36:15.382607: I tao_bridge/kernels/tao_compilation_cache.cc:363]     async compilation: 0
2022-07-13 02:36:15.382614: I tao_bridge/kernels/tao_compilation_cache.cc:364]     profiling guide compilation: 0
2022-07-13 02:37:25.311418: W tao_bridge/kernels/disc_launch.cc:46] cluster: tao_cluster_0_disc_launch fallbacks to TF as load DSO failed, file: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so, error: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so: cannot open shared object file: No such file or directory
2022-07-13 02:37:25.365281: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2022-07-13 02:37:25.860844: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2022-07-13 02:37:25.927966: W tao_bridge/kernels/disc_launch.cc:46] cluster: tao_cluster_0_disc_launch fallbacks to TF as load DSO failed, file: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so, error: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so: cannot open shared object file: No such file or directory
2022-07-13 02:37:25.985445: W tao_bridge/kernels/disc_launch.cc:46] cluster: tao_cluster_0_disc_launch fallbacks to TF as load DSO failed, file: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so, error: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so: cannot open shared object file: No such file or directory
2022-07-13 02:37:26.042850: W tao_bridge/kernels/disc_launch.cc:46] cluster: tao_cluster_0_disc_launch fallbacks to TF as load DSO failed, file: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so, error: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so: cannot open shared object file: No such file or directory
2022-07-13 02:37:26.100236: W tao_bridge/kernels/disc_launch.cc:46] cluster: tao_cluster_0_disc_launch fallbacks to TF as load DSO failed, file: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so, error: /tmp/tempfile-75849d5b-8594-5e3a6a62a1edf.output.so: cannot open shared object file: No such file or directory
Run 10 inferences with dynamic batch sizes.
